### ISSUE TITLE
We need images that represent these categories so that users will be able to click those images to perform category search

### ISSUE THREAD

**Issue by kaanozgen12** [kaanozgen12/HoneyBadgersApp#1]
{
        "id": 1,
        "title": "Websites, IT and Software"
    },
    {
        "id": 2,
        "title": "Mobile Phones and Computing"
    },
    {
        "id": 3,
        "title": "Translation and Languages"
    },
    {
        "id": 4,
        "title": "Engineering and Science"
    },
    {
        "id": 5,
        "title": "Writing and Content"
    },
    {
        "id": 6,
        "title": "Sales and Marketing"
    },
    {
        "id": 7,
        "title": "Design, Media and Architecture"
    },
    {
        "id": 8,
        "title": "Other"
    }
]

**Comment by canberky** [comment]
Done.
